# filebeat.inputs:
# - type: log
#   enabled: false
#   paths:
#     - /var/log/*.log
# - type: filestream
#   enabled: false
#   paths:
#     - /var/log/*.log

# filebeat.config.modules:
#   path: ${path.config}/modules.d/*.yml
#   reload.enabled: false

# setup.template.settings:
#   index.number_of_shards: 1
# setup.dashboards.enabled: true

# setup.kibana:
#   host: "localhost:5601"
#   username: "elastic"
#   password: "password"

# output.elasticsearch:
#   hosts: ["localhost:9200"]
#   username: "elastic"
#   password: "password"
#   pipeline: geoip-info

# processors:
#   - add_host_metadata:
#       when.not.contains.tags: forwarded
#   - add_cloud_metadata: ~
#   - add_docker_metadata: ~
#   - add_kubernetes_metadata: ~


filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: "elastic"
  password: "password"
  pipeline: geoip-info


